-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        -- col = {
        --     active_border = {
        --         colors = {"rgba(33ccffee)", "rgba(00ff99ee)"},
        --         angle = 45,
        --     },
        -- },
        layout = "dwindle",
        snap = {
            enabled = false,
        },
    },
})

-- Keybinds

hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))

hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())

hl.unbind("SUPER + SHIFT + Q")
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.kill())


